/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFurnitureRouteImport } from './routes/_authenticated/furniture'
import { Route as AuthenticatedClothesRouteImport } from './routes/_authenticated/clothes'
import { Route as AuthenticatedBlessingDistributionRouteImport } from './routes/_authenticated/blessing-distribution'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAddRouteImport } from './routes/_authenticated/add'
import { Route as AuthenticatedIndividualIdRouteImport } from './routes/_authenticated/individual.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFurnitureRoute = AuthenticatedFurnitureRouteImport.update({
  id: '/furniture',
  path: '/furniture',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClothesRoute = AuthenticatedClothesRouteImport.update({
  id: '/clothes',
  path: '/clothes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlessingDistributionRoute =
  AuthenticatedBlessingDistributionRouteImport.update({
    id: '/blessing-distribution',
    path: '/blessing-distribution',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddRoute = AuthenticatedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndividualIdRoute =
  AuthenticatedIndividualIdRouteImport.update({
    id: '/individual/$id',
    path: '/individual/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/add': typeof AuthenticatedAddRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/blessing-distribution': typeof AuthenticatedBlessingDistributionRoute
  '/clothes': typeof AuthenticatedClothesRoute
  '/furniture': typeof AuthenticatedFurnitureRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/search': typeof AuthenticatedSearchRoute
  '/individual/$id': typeof AuthenticatedIndividualIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/add': typeof AuthenticatedAddRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/blessing-distribution': typeof AuthenticatedBlessingDistributionRoute
  '/clothes': typeof AuthenticatedClothesRoute
  '/furniture': typeof AuthenticatedFurnitureRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/search': typeof AuthenticatedSearchRoute
  '/': typeof AuthenticatedIndexRoute
  '/individual/$id': typeof AuthenticatedIndividualIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/add': typeof AuthenticatedAddRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/blessing-distribution': typeof AuthenticatedBlessingDistributionRoute
  '/_authenticated/clothes': typeof AuthenticatedClothesRoute
  '/_authenticated/furniture': typeof AuthenticatedFurnitureRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/individual/$id': typeof AuthenticatedIndividualIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/add'
    | '/audit'
    | '/blessing-distribution'
    | '/clothes'
    | '/furniture'
    | '/inventory'
    | '/pharmacy'
    | '/search'
    | '/individual/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/add'
    | '/audit'
    | '/blessing-distribution'
    | '/clothes'
    | '/furniture'
    | '/inventory'
    | '/pharmacy'
    | '/search'
    | '/'
    | '/individual/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/add'
    | '/_authenticated/audit'
    | '/_authenticated/blessing-distribution'
    | '/_authenticated/clothes'
    | '/_authenticated/furniture'
    | '/_authenticated/inventory'
    | '/_authenticated/pharmacy'
    | '/_authenticated/search'
    | '/_authenticated/'
    | '/_authenticated/individual/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/furniture': {
      id: '/_authenticated/furniture'
      path: '/furniture'
      fullPath: '/furniture'
      preLoaderRoute: typeof AuthenticatedFurnitureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clothes': {
      id: '/_authenticated/clothes'
      path: '/clothes'
      fullPath: '/clothes'
      preLoaderRoute: typeof AuthenticatedClothesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blessing-distribution': {
      id: '/_authenticated/blessing-distribution'
      path: '/blessing-distribution'
      fullPath: '/blessing-distribution'
      preLoaderRoute: typeof AuthenticatedBlessingDistributionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add': {
      id: '/_authenticated/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthenticatedAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/individual/$id': {
      id: '/_authenticated/individual/$id'
      path: '/individual/$id'
      fullPath: '/individual/$id'
      preLoaderRoute: typeof AuthenticatedIndividualIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddRoute: typeof AuthenticatedAddRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBlessingDistributionRoute: typeof AuthenticatedBlessingDistributionRoute
  AuthenticatedClothesRoute: typeof AuthenticatedClothesRoute
  AuthenticatedFurnitureRoute: typeof AuthenticatedFurnitureRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedIndividualIdRoute: typeof AuthenticatedIndividualIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddRoute: AuthenticatedAddRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBlessingDistributionRoute:
    AuthenticatedBlessingDistributionRoute,
  AuthenticatedClothesRoute: AuthenticatedClothesRoute,
  AuthenticatedFurnitureRoute: AuthenticatedFurnitureRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedIndividualIdRoute: AuthenticatedIndividualIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
